version: "3.8"

services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:9090"
    environment:
      - POSTGRES_HOST=postgesql
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
      - postgesql
    networks:
      - web_api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api

  postgesql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dvdrental
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api


networks:
  web_api:
    driver: bridge